config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  devise_for :users,
             controllers: {
               confirmations: "users/confirmations",
               registrations: "users/registrations",
               invitations: "users/invitations",
               passwords: "users/passwords",
               two_factor_authentication: "users/two_factor_authentication",
             }

  devise_scope :user do
    put "users/confirmations", to: "users/confirmations#update"
    get "users/confirmations/pending", to: "users/confirmations#pending"

    put "users/two_factor_authentication_setup", to: "users/two_factor_authentication_setup#update"
    get "users/two_factor_authentication_setup", to: "users/two_factor_authentication_setup#show"

    get "users/:id/two_factor_authentication/edit", to: "users/two_factor_authentication#edit"
    delete "users/:id/two_factor_authentication", to: "users/two_factor_authentication#destroy"
  end
  get "confirm_new_membership", to: "users/memberships#create"

  get "/healthcheck", to: "monitoring#healthcheck"
  get "change_organisation", to: "current_organisation#edit"
  patch "change_organisation", to: "current_organisation#update"

  resources :status, only: %i[index]
  resources :ips, only: %i[index new create destroy] do
    get "remove", to: "ips#index"
    get "created", to: "ips#index", on: :collection
    get "created/location", to: "ips#index", on: :collection
    get "removed", to: "ips#index", on: :collection
    get "removed/location", to: "ips#index", on: :collection
  end

  resources :help, only: %i[create new] do
    get "/", on: :collection, to: "help#new"
    get "signed_in", on: :new
    get "admin_account", on: :new
    get "technical_support", on: :new
    get "user_support", on: :new
  end
  resources :locations, only: %i[new create destroy update] do
    get "remove", to: "ips#index"
    get "rotate_key", to: "ips#index"
    get "add_ips", to: "add_ips"
    patch "update_ips", to: "update_ips"
  end
  resources :memberships, only: %i[edit update index destroy] do
    collection do
      get "created/invite", to: "memberships#index"
      get "updated/permissions", to: "memberships#index"
      get "removed", to: "memberships#index"
    end
  end
  resources :mou, only: %i[index create] do
    collection do
      get "created", to: "mou#index"
      get "replaced", to: "mou#index"
    end
  end
  resources :logs, only: %i[index]
  resources :logs_searches, path: "logs/search", only: %i[new index create] do
    get "ip", on: :new
    get "username", on: :new
    get "location", on: :new
  end
  resources :organisations, only: %i[new create edit update]
  resources :settings, only: %i[index] do
    collection do
      get "initial", to: "settings#index", as: :new_organisation
    end
  end
  get "setup_instructions", to: redirect("settings")
  get "setup_instructions/:path", to: redirect("settings/%{path}")

  resources :overview, only: %i[index]

  namespace :super_admin do
    resources :locations, only: %i[index] do
      collection do
        get "map", to: "locations/map#index"
      end
    end
    resources :mou, only: %i[index update create]
    resources :organisations, only: %i[index show destroy] do
      collection do
        get "service_emails", to: "organisations#service_emails", constraints: { format: "csv" }
      end
    end
    resource :whitelist, only: %i[new create] do
      scope module: "whitelists" do
        resources :email_domains, only: %i[index new create destroy]
        resources :organisation_names, only: %i[index create destroy]
      end
    end

    post "wifi_user_search", to: "wifi_user_search#search"

    namespace "neo" do
      get "dashboard"
    end
  end

  %w[404 422 500].each do |code|
    get code, to: "application#error", code: code
  end
end

app/controllers/organisations/mou_controller.rb
class Organisations::MouController < ApplicationController
  def index
    @mou = AdminConfig.mou
  end

  def create
    if params[:signed_mou]
      current_organisation.signed_mou.attach(params[:signed_mou])
      flash[:notice] = "MOU uploaded successfully."
    else
      flash[:alert] = "Choose a file before uploading "
    end
    redirect_to organisations_mou_index_path
  end
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
  before_action :set_organisation, only: %i[edit update]
  before_action :validate_user_is_part_of_organisation, only: %i[edit update]

  attr_reader :hide_sidebar

  def new
    @organisation = Organisation.new
    @register_organisations = Organisation.fetch_organisations_from_register

    @hide_sidebar = true
  end

  def create
    @organisation = Organisation.new(organisation_params)

    if @organisation.save
      assign_user_to_organisation(@organisation)
      set_as_current_organisation(@organisation)

      redirect_to root_path, notice: "#{@organisation.name} created"
    else
      @register_organisations = Organisation.fetch_organisations_from_register

      render :new
    end
  end

  def edit; end

  def update
    if @organisation.update(organisation_params)
      redirect_to settings_path, notice: "Service email updated"
    else
      render :edit
    end
  end

private

  def sidebar
    @hide_sidebar ? :empty : super
  end

  def set_organisation
    @organisation = Organisation.find(params.fetch(:id))
  end

  def validate_user_is_part_of_organisation
    unless user_belongs_to_same_org
      raise ActionController::RoutingError, "Not Found"
    end
  end

  def user_belongs_to_same_org
    current_organisation == @organisation
  end

  def assign_user_to_organisation(organisation)
    current_user.memberships.create(
      organisation: organisation,
      confirmed_at: Time.zone.now,
    )
  end

  def set_as_current_organisation(organisation)
    session[:organisation_id] = organisation.id
  end

  def organisation_params
    params.require(:organisation).permit(:service_email, :name)
  end
end

app/controllers/super_admin/locations/map_controller.rb
class SuperAdmin::Locations::MapController < SuperAdminController
  def index
    @postcodes = Location.pluck(:postcode)
    @coordinates = convert_postcodes_to_coordinates
  end

  def convert_postcodes_to_coordinates
    UseCases::Administrator::GetPostcodeCoordinates.new(
      postcodes_gateway: Gateways::Coordinates.new(postcodes: @postcodes),
    ).execute
  end
end

app/controllers/super_admin/locations_controller.rb
class SuperAdmin::LocationsController < SuperAdminController
  def index
    @locations = Location.order("#{sort_column} #{sort_direction}").includes(:organisation)
  end

private

  def sortable_columns
    %w[address]
  end

  def sort_column
    sortable_columns.include?(params[:sort]) ? params[:sort] : "address"
  end

  def sort_direction
    directions = %w[asc]
    directions.include?(params[:direction]) ? params[:direction] : directions.first
  end
end

app/controllers/super_admin/mou_controller.rb
class SuperAdmin::MouController < SuperAdminController
  def index
    @mou = AdminConfig.mou
  end

  def create
    if params[:id]
      organisation = Organisation.find(params[:id])
      attach_to_organisation(organisation)
      redirect_to super_admin_organisation_path(organisation)
    else
      attach_to_template
    end
  end

private

  def attach_to_organisation(organisation)
    if params[:signed_mou]
      mime_type = Marcel::MimeType.for(params[:signed_mou])
      if mime_type.to_s == "application/pdf"
        organisation.signed_mou.attach(params[:signed_mou])
        flash[:notice] = "MOU uploaded successfully."
      else
        flash[:alert] = "Unsupported file type. Signed MOU should be a PDF."
      end
    else
      flash[:alert] = "No MoU file selected. Please select a file and try again."
    end
  end

  def attach_to_template
    if params[:unsigned_document]
      mime_type = Marcel::MimeType.for(params[:unsigned_document])
      if mime_type.to_s == "application/pdf"
        AdminConfig.mou.unsigned_document.attach(params[:unsigned_document])
        flash[:notice] = "MOU template uploaded successfully."
      else
        flash[:alert] = "Unsupported file type. MOU template should be a PDF."
      end
    else
      flash[:alert] = "No MoU template selected. Please select a file and try again."
    end
    redirect_to super_admin_mou_index_path
  end
end

app/controllers/super_admin/neo_controller.rb
class SuperAdmin::NeoController < SuperAdminController
  def dashboard
    @manage_link =
      if current_user.new_super_admin?
        overview_index_path
      else
        root_path
      end
  end

protected

  def subnav
    :neo
  end

  def current_organisation; end

  def redirect_user_with_no_organisation; end

  def sidebar
    :super_admin
  end
end

app/controllers/super_admin/organisations_controller.rb
class SuperAdmin::OrganisationsController < SuperAdminController
  helper_method :sort_column, :sort_direction

  def index
    @organisations = Organisation.sortable_with_child_counts(sort_column, sort_direction)

    @location_count = Location.count

    respond_to do |format|
      format.html
      format.csv { send_data Organisation.all_as_csv, filename: "organisations.csv" }
    end
  end

  def service_emails
    respond_to do |format|
      format.csv { send_data Organisation.service_emails_as_csv, filename: "service_emails.csv" }
    end
  end

  def show
    @organisation = Organisation.find(params[:id])
    @team = sorted_team_members(@organisation)
    @pagy, @locations = pagy(@organisation.locations.order("address asc"))
  end

  def destroy
    organisation = Organisation.find(params[:id])
    organisation.destroy!
    publish_organisation_names
    redirect_to super_admin_organisations_path, notice: "Organisation has been removed"
  end

private

  def sorted_team_members(organisation)
    UseCases::Administrator::SortUsers.new(
      users_gateway: Gateways::OrganisationUsers.new(organisation: organisation),
    ).execute
  end

  def publish_organisation_names
    UseCases::Administrator::PublishOrganisationNames.new(
      destination_gateway: Gateways::S3.new(
        bucket: ENV.fetch("S3_PRODUCT_PAGE_DATA_BUCKET"),
        key: ENV.fetch("S3_ORGANISATION_NAMES_OBJECT_KEY"),
      ),
      source_gateway: Gateways::OrganisationNames.new,
      presenter: UseCases::Administrator::FormatOrganisationNames.new,
    ).execute
  end

  def sortable_columns
    %w[name created_at locations_count ips_count active_storage_attachments.created_at]
  end

  def sort_column
    sortable_columns.include?(params[:sort]) ? params[:sort] : "created_at"
  end

  def sort_direction
    directions = %w[desc asc]
    directions.include?(params[:direction]) ? params[:direction] : directions.first
  end
end

app/controllers/super_admin/whitelists/email_domains_controller.rb
class SuperAdmin::Whitelists::EmailDomainsController < SuperAdminController
  helper_method :sort_column, :sort_direction

  def index
    @authorised_email_domains = AuthorisedEmailDomain.all.order("#{sort_column} #{sort_direction}")
  end

  def new
    @authorised_email_domain = AuthorisedEmailDomain.new
  end

  def create
    @authorised_email_domain = AuthorisedEmailDomain.new(authorised_email_params)

    if @authorised_email_domain.save
      publish_email_domains_regex
      publish_email_domains_list

      redirect_to super_admin_whitelist_email_domains_path, notice: "#{@authorised_email_domain.name} authorised"
    else
      render :new
    end
  end

  def destroy
    authorised_email_domain = AuthorisedEmailDomain.find_by(id: params.fetch(:id))

    authorised_email_domain.destroy!
    publish_email_domains_regex
    publish_email_domains_list

    redirect_to super_admin_whitelist_email_domains_path, notice: "#{authorised_email_domain.name} has been deleted"
  end

private

  def publish_email_domains_regex
    UseCases::Administrator::PublishSignupWhitelist.new(
      destination_gateway: Gateways::S3.new(
        bucket: ENV.fetch("S3_SIGNUP_WHITELIST_BUCKET"),
        key: ENV.fetch("S3_SIGNUP_WHITELIST_OBJECT_KEY"),
      ),
      source_gateway: Gateways::AuthorisedEmailDomains.new,
      presenter: UseCases::Administrator::FormatEmailDomainsRegex.new,
    ).execute
  end

  def publish_email_domains_list
    UseCases::Administrator::PublishSignupWhitelist.new(
      destination_gateway: Gateways::S3.new(
        bucket: ENV.fetch("S3_PRODUCT_PAGE_DATA_BUCKET"),
        key: ENV.fetch("S3_EMAIL_DOMAINS_OBJECT_KEY"),
      ),
      source_gateway: Gateways::AuthorisedEmailDomains.new,
      presenter: UseCases::Administrator::FormatEmailDomainsList.new,
    ).execute
  end

  def authorised_email_params
    params.require(:authorised_email_domain).permit(:name)
  end

  def sortable_columns
    %w[name]
  end

  def sortable_directions
    %w[asc]
  end

  def sort_column
    sortable_columns.include?(params[:sort]) ? params[:sort] : sortable_columns.first
  end

  def sort_direction
    sortable_directions.include?(params[:direction]) ? params[:direction] : sortable_directions.first
  end
end

app/controllers/super_admin/whitelists/organisation_names_controller.rb
class SuperAdmin::Whitelists::OrganisationNamesController < SuperAdminController
  helper_method :sort_column, :sort_direction

  before_action :set_organisations_from_register, only: %i[create index]

  def index
    @custom_organisation_names = ordered_custom_orgs
    @custom_organisation = CustomOrganisationName.new
  end

  def create
    @custom_organisation_names = ordered_custom_orgs
    @custom_organisation = CustomOrganisationName.new(custom_org_params)

    if @custom_organisation.save
      redirect_to super_admin_whitelist_organisation_names_path, notice: "Custom organisation has been successfully added"
    else
      render :index
    end
  end

  def destroy
    custom_org = CustomOrganisationName.find(params.fetch(:id))

    custom_org.destroy!
    redirect_to super_admin_whitelist_organisation_names_path, notice: "Successfully removed #{custom_org.name}"
  end

private

  def custom_org_params
    params.require(:custom_organisations).permit(:name)
  end

  def ordered_custom_orgs
    CustomOrganisationName.all.order("#{sort_column} #{sort_direction}")
  end

  def sortable_columns
    %w[name]
  end

  def sortable_directions
    %w[asc]
  end

  def sort_column
    sortable_columns.include?(params[:sort]) ? params[:sort] : sortable_columns.first
  end

  def sort_direction
    sortable_directions.include?(params[:direction]) ? params[:direction] : sortable_directions.first
  end

  def set_organisations_from_register
    @fetched_organisations_from_register = Organisation.fetch_organisations_from_register
  end
end

app/controllers/super_admin/wifi_user_search_controller.rb
class SuperAdmin::WifiUserSearchController < SuperAdminController
  def search
    if search_term.blank?
      flash.now[:alert] = "Search term can't be blank"
    else
      @wifi_user = WifiUser.search(search_term.gsub(" ", ""))
    end

    render "logs_searches/contact"
  end

private

  def search_term
    params[:search_term]
  end
end

app/controllers/super_admin_controller.rb
class SuperAdminController < ApplicationController
  before_action :authorise_admin

  def authorise_admin
    redirect_to root_path unless super_admin?
  end

protected

  def sidebar
    if current_organisation&.super_admin?
      :super_org
    else
      super
    end
  end
end

app/helpers/organisations_helper.rb
module OrganisationsHelper
  def sort_link(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, { sort: column, direction: direction }, class: css_class
  end
end

app/views/super_admin/organisations/_confirm_remove_organisation.html.erb
<div class="govuk-error-summary" role="alert">
  <h2 class="govuk-error-summary__title">
    Are you sure you want to delete <%= @organisation.name %>?
  </h2>

  <div class="govuk-error-summary__body">
    <table class="govuk-table">
      <tbody class="govuk-table__body">
        <tr class="govuk-table__row">
        </tr>
      </tbody>
    </table>

     <%= button_to "Yes, remove this organisation", super_admin_organisation_path(@organisation), method: :delete, class: "govuk-button red-button" %>
  </div>
</div>

app/views/super_admin/organisations/_ips.html.erb
<table class="govuk-table govuk-!-margin-bottom-7">
  <tbody class="govuk-table__body" id="ips-table">
  <% ips.each do |ip| %>
    <tr class="govuk-table__row" id="ips-row-<%= ip.id %>">
      <td class="govuk-table__cell govuk-!-width-one-third">
        <%= render partial: "ip_address", locals: { ip: ip.address } %>
      </td>
      <% if ip.available? %>
        <td class="govuk-table__cell ">
          <% if ip.unused? %>
            No traffic received yet
          <% elsif ip.inactive? %>
            No traffic in the last 10 days
          <% else %>
            Receiving traffic (<%= link_to "view logs", logs_path(ip: ip.address), class: "govuk-link" %>)
          <% end %>
        </td>
      <% else %>
        <td class="govuk-table__cell text-dark-grey">
          Available at 6am tomorrow
        </td>
      <% end %>
      <td class="govuk-table__cell text-right">
        <% if current_user.can_manage_locations?(current_organisation) %>
          <%= link_to "Remove", ip_remove_path(ip), class: "govuk-link govuk-link--no-visited-state" %>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/super_admin/organisations/_locations.html.erb
<% if locations.any? %>
  <table class="govuk-table">
    <thead class="govuk-table__head">
    </thead>
    <tbody class="govuk-table__body">
      <% locations.each do |location| %>
        <tr class="govuk-table__row">
          <td class="govuk-table__cell" scope="row"><%= location.address %></td>
          <td class="govuk-table__cell text-right" scope="row"><%= location.postcode %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p class="govuk-body">This organisation has no locations.</p>
<% end %>

app/views/super_admin/organisations/_mou_form.html.erb
<% mou_attached = organisation.signed_mou.attached? %>

<% if mou_attached %>
  <p class="govuk-body">
    A signed MOU was uploaded on <%= organisation.signed_mou.attachment.created_at.strftime("%e %b %Y") %>,
    <%= link_to "download and view the document.", rails_blob_path(organisation.signed_mou, disposition: "attachment"), class: "govuk-link" %>
  </p>

  <h2 class="govuk-heading-m">Replace MOU</h2>
  <p class="govuk-body">Manually replace this organisation's signed MOU. This will overwrite the existing document.</p>
<% else %>
  <p class="govuk-body">This organisation has not uploaded an MOU.</p>
  <h2 class="govuk-heading-m">Upload MOU</h2>
  <p class="govuk-body">Manually upload this organisation's signed MOU</p>
<% end %>

<div id="mou-upload-form">
  <%= form_with url: super_admin_mou_index_path(id: organisation.id), local: true, method: "post" do |form| %>
    <div class="govuk-form-group">
      <%= form.file_field(:signed_mou, class: "govuk-file-upload") %>
    </div>

    <% submit_text = mou_attached ? "Replace MOU" : "Upload MOU" %>
    <%= form.submit(submit_text, class: "govuk-button") %>
  <% end %>
</div>

app/views/super_admin/organisations/_section.html.erb
<% heading ||= nil %>
<div class="govuk-grid-row govuk-!-margin-bottom-8">
  <div class="govuk-grid-column-full">
    <% if heading %>
      <h2 class="govuk-heading-l govuk-!-margin-bottom-0"><%= heading %></h2>
      <hr class="govuk-section-break govuk-section-break--visible govuk-section-break--m govuk-!-margin-top-0">
    <% end %>

    <%= yield %>
  </div>
</div>

app/views/super_admin/organisations/_team.html.erb
<% if team.any? %>
  <table class="govuk-table">
    <thead class="govuk-table__head">
    </thead>
    <tbody class="govuk-table__body">
      <% team.each do |user| %>
        <tr class="govuk-table__row">
          <td class="govuk-table__cell" scope="row"><%= user.name %></td>
          <td class="govuk-table__cell text-right" scope="row"><%= user.email %></td>
          <td class="govuk-table__cell text-right" scope="row">
            <%= link_to edit_membership_path(user.membership_for(@organisation), remove_team_member: true),
                        class: "govuk-button red-button" do %>
              Remove user <span class='govuk-visually-hidden'>- <%= user.email %></span>
            <% end %>
          </td>
          <td class="govuk-table__cell text-right" scope="row">
            <% if user.totp_enabled? %>
              <%= link_to({ controller: "users/two_factor_authentication", action: "edit", id: user },
                          class: "govuk-button govuk-button--secondary") do %>
                Reset 2FA <span class='govuk-visually-hidden'>for <%= user.email %></span>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p class="govuk-body">This organisation has no team members.</p>
<% end %>

app/views/super_admin/organisations/_usage.html.erb
<div class="govuk-grid-row">
  <div class="govuk-grid-column-one-half">
    <p class="govuk-body">
      <strong class="govuk-!-font-size-36" id="location-count">
        <%= organisation.locations.count %>
      </strong><br>
      Locations
    </p>
  </div>

  <div class="govuk-grid-column-one-half">
    <p class="govuk-body">
      <strong class="govuk-!-font-size-36" id="ip-count">
        <%= organisation.ips.count %>
      </strong><br>
      IP addresses
    </p>
  </div>

  <div class="govuk-grid-column-one-half">
    <p class="govuk-body">
      <strong class="govuk-!-font-size-36" id="user-count">
        <%= organisation.users.count %>
      </strong><br>
      Team members
    </p>
  </div>
</div>

app/views/super_admin/organisations/index.html.erb
<% content_for :page_title, "All organisations" %>

<h1 class="govuk-heading-l">All organisations</h1>
<p class="govuk-body">
  GovWifi is in
  <span class="govuk-!-font-weight-bold">
    <%= pluralize(@location_count, "location") %>
  </span>
   across
  <span class="govuk-!-font-weight-bold">
    <%= pluralize(@organisations.length, "organisation") %>.
  </span>
</p>

<div class="govuk-!-margin-top-1">
  <%= link_to "Download all organisations in CSV format",
              super_admin_organisations_path(format: "csv"),
              class: "govuk-link" %>
  <br />
  <%= link_to "Download all service emails in CSV format",
              service_emails_super_admin_organisations_path(format: "csv"),
              class: "govuk-link" %>
</div>
<p>
  <label class="govuk-label" for="filter-input">Search by organisation name</label>
  <input type="search" id="filter-input" class="govuk-input" autocomplete="off">
</p>

<table class="govuk-table">
  <thead class="govuk-table__head">
    <tr class="govuk-table__row">
      <th class="govuk-table__header govuk-!-width-one-half"><%= sort_link "name" %></th>
      <th class="govuk-table__header"><%= sort_link "created_at", "Created on" %></th>
      <th class="govuk-table__header govuk-table__header"><%= sort_link "active_storage_attachments.created_at", "MOU Signed" %></th>
      <th class="govuk-table__header govuk-table__header--numeric"><%= sort_link "locations_count", "Locations" %></th>
      <th class="govuk-table__header govuk-table__header--numeric"><%= sort_link "ips_count", "IPs" %></th>
    </tr>
  </thead>
  <tbody class="govuk-table__body" aria-live="polite">
    <% @organisations.each do |organisation| %>
      <tr class="govuk-table__row result-row">
        <td class="govuk-table__cell govuk-!-width-one-half" scope="row">
          <%= link_to organisation.name, super_admin_organisation_path(organisation), class: "govuk-link filter-by" %>
        </td>
        <td class="govuk-table__cell" scope="row">
          <%= organisation.created_at.strftime("%e %b %Y") %>
        </td>
        <td class="govuk-table__cell govuk-table__cell" scope="row">
          <% if organisation.signed_mou.attached? %>
            <%= organisation.signed_mou.attachment.created_at.strftime("%e %b %Y") %>
          <% else %>
            -
          <% end %>
        </td>
        <td class="govuk-table__cell govuk-table__cell--numeric" scope="row">
          <%= organisation.locations.count %>
        </td>
        <td class="govuk-table__cell govuk-table__cell--numeric" scope="row">
          <%= organisation.ips.count %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div aria-role="status">
  <p class="govuk-body" id="no-results" style="display: none">
    <strong>No results found</strong>
  </p>
</div>

<%= render "shared/filter_search" %>

app/views/super_admin/organisations/show.html.erb
<% content_for :page_title, @organisation.name.to_s %>

<div class="govuk-grid-row">
  <%= render "confirm_remove_organisation" if params[:remove_organisation] %>

  <div class="govuk-grid-column-full">
    <%= link_to "Back to list", super_admin_organisations_path, class: "govuk-back-link" %>

    <h1 class="govuk-heading-xl govuk-!-margin-bottom-2 govuk-!-margin-top-2">
      <%= @organisation.name %>
    </h1>

    <p class="govuk-body govuk-!-margin-bottom-8">
      GovWifi organisation since <%= @organisation.created_at.strftime(
                                       "#{@organisation.created_at.day.ordinalize} of %B, %Y",
                                     ) %>
    </p>

    <%= render "section", heading: "Usage" do %>
      <%= render "usage", organisation: @organisation %>
    <% end %>

    <%= render "section", heading: "Service Email" do %>
      <p class="govuk-body"><%= @organisation.service_email %></p>
    <% end %>

    <%= render "section", heading: "Team" do %>
      <% if current_user.can_manage_team?(current_organisation) %>
        <%= link_to "Add team member", new_user_invitation_path(organisation_id: @organisation.id), class: "govuk-button", role: "button", draggable: "false", "data-module" => "govuk-button" %>
      <% end %>
      <%= render "team", team: @team %>
    <% end %>

    <%= render "section", heading: "MoU" do %>
      <%= render "mou_form", organisation: @organisation %>
    <% end %>

    <%= render "section", heading: "Locations" do %>
      <%== pagy_nav_govuk(@pagy) %>
      <%= render "locations", locations: @locations %>
    <% end %>

    <%= render "section", heading: "IPs" do %>
      <% @locations.each do |location| %>
        <%= render partial: "shared/manage_ips", locals: { location: location, show_ip_controls: false } %>
      <% end %>
    <% end %>
    <%== pagy_nav_govuk(@pagy) %>
    <%= link_to "Delete organisation", super_admin_organisation_path(@organisation, remove_organisation: true), class: "govuk-button red-button", role: "button", draggable: "false", "data-module" => "govuk-button" %>
  </div>
</div>