config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  devise_for :users,
             controllers: {
               confirmations: "users/confirmations",
               registrations: "users/registrations",
               invitations: "users/invitations",
               passwords: "users/passwords",
               two_factor_authentication: "users/two_factor_authentication",
             }

  devise_scope :user do
    put "users/confirmations", to: "users/confirmations#update"
    get "users/confirmations/pending", to: "users/confirmations#pending"

    put "users/two_factor_authentication_setup", to: "users/two_factor_authentication_setup#update"
    get "users/two_factor_authentication_setup", to: "users/two_factor_authentication_setup#show"

    get "users/:id/two_factor_authentication/edit", to: "users/two_factor_authentication#edit"
    delete "users/:id/two_factor_authentication", to: "users/two_factor_authentication#destroy"
  end
  get "confirm_new_membership", to: "users/memberships#create"

  get "/healthcheck", to: "monitoring#healthcheck"
  get "change_organisation", to: "current_organisation#edit"
  patch "change_organisation", to: "current_organisation#update"

  resources :status, only: %i[index]
  resources :ips, only: %i[index new create destroy] do
    get "remove", to: "ips#index"
    get "created", to: "ips#index", on: :collection
    get "created/location", to: "ips#index", on: :collection
    get "removed", to: "ips#index", on: :collection
    get "removed/location", to: "ips#index", on: :collection
  end

  resources :help, only: %i[create new] do
    get "/", on: :collection, to: "help#new"
    get "signed_in", on: :new
    get "admin_account", on: :new
    get "technical_support", on: :new
    get "user_support", on: :new
  end
  resources :locations, only: %i[new create destroy update] do
    get "remove", to: "ips#index"
    get "rotate_key", to: "ips#index"
    get "add_ips", to: "add_ips"
    patch "update_ips", to: "update_ips"
  end
  resources :memberships, only: %i[edit update index destroy] do
    collection do
      get "created/invite", to: "memberships#index"
      get "updated/permissions", to: "memberships#index"
      get "removed", to: "memberships#index"
    end
  end
  resources :mou, only: %i[index create] do
    collection do
      get "created", to: "mou#index"
      get "replaced", to: "mou#index"
    end
  end
  resources :logs, only: %i[index]
  resources :logs_searches, path: "logs/search", only: %i[new index create] do
    get "ip", on: :new
    get "username", on: :new
    get "location", on: :new
  end
  resources :organisations, only: %i[new create edit update]
  resources :settings, only: %i[index] do
    collection do
      get "initial", to: "settings#index", as: :new_organisation
    end
  end
  get "setup_instructions", to: redirect("settings")
  get "setup_instructions/:path", to: redirect("settings/%{path}")

  resources :overview, only: %i[index]

  namespace :super_admin do
    resources :locations, only: %i[index] do
      collection do
        get "map", to: "locations/map#index"
      end
    end
    resources :mou, only: %i[index update create]
    resources :organisations, only: %i[index show destroy] do
      collection do
        get "service_emails", to: "organisations#service_emails", constraints: { format: "csv" }
      end
    end
    resource :whitelist, only: %i[new create] do
      scope module: "whitelists" do
        resources :email_domains, only: %i[index new create destroy]
        resources :organisation_names, only: %i[index create destroy]
      end
    end

    post "wifi_user_search", to: "wifi_user_search#search"

    namespace "neo" do
      get "dashboard"
    end
  end

  %w[404 422 500].each do |code|
    get code, to: "application#error", code: code
  end
end

app/models/logs_search.rb
class LogsSearch
  include ActiveModel::Model

  attr_accessor :filter, :first_step, :search_term

  validates :search_term, presence: { message: "cannot be empty" }
  validates :search_term,
            length: { in: 5..6, message: "must be 5 or 6 characters" },
            if: -> { filter == "username" }
  validates :search_term, with: :validate_ip, if: -> { filter == "ip" }

private

  def validate_ip
    ip_check = UseCases::Administrator::CheckIfValidIp.new.execute(search_term)
    unless ip_check[:success]
      errors.add(:search_term, "must be a valid IP address")
    end
  end
end

app/controllers/admin/logs_searches_controller.rb
class Admin::LogsSearchesController < AdminController
  def create
    @search = LogsSearch.new(search_params)

    @search.first_step ? filter_choice : term_choice
  end

  def filter_choice
    if @search.filter.present?
      render @search.filter
    else
      @search.errors.add(:filter, "can't be blank")
      render 'new'
    end
  end

  def username
    @search = LogsSearch.new(filter: 'username')
  end

private

  def search_params
    params.require(:logs_search).permit(:filter, :term, :first_step)
  end
end

app/controllers/logs_searches_controller.rb
class LogsSearchesController < ApplicationController
  def create
    @search = LogsSearch.new(search_params)
    @locations = ordered_locations

    @search.first_step ? filter_choice : term_choice
  end

  def filter_choice
    if @search.filter.present?
      render @search.filter
    else
      @search.errors.add(:filter, "can't be blank")
      render "new"
    end
  end

  def term_choice
    if @search.valid?
      redirect_to logs_path(@search.filter.to_sym => @search.search_term)
    else
      render @search.filter
    end
  end

  def ip
    @search = LogsSearch.new(filter: "ip")
  end

  def username
    @search = LogsSearch.new(filter: "username")
  end

  def location
    @search = LogsSearch.new(filter: "location")
    @locations = ordered_locations
  end

private

  def search_params
    params.require(:logs_search)
      .permit(:filter, :first_step, :search_term)
      .each { |_, v| v.strip! }
  end

  def ordered_locations
    current_organisation.locations.order([:address])
  end
end

app/views/logs_searches/choice.html.erb
<div class='govuk-grid-row'>
  <h1 class='govuk-heading-l govuk-grid-column-full'>Logs</h1>

  <div class='govuk-grid-column-full'>
    <p class='govuk-body'>
      We log requests from your organisation to the GovWifi service.
    </p>

    <%= form_with url: new_logs_search_path, method: :get do |form| %>
      <div class="govuk-form-group">
        <span id="changed-name-hint" class="govuk-hint">
          Search these logs by
        </span>
        <div class="govuk-radios govuk-radios--inline">
          <div class="govuk-radios__item">
            <input class="govuk-radios__input" id="choice-ip" name="choice" type="radio" value="ip">
            <label class="govuk-label govuk-radios__label" for="choice-ip">
              IP address
            </label>
          </div>
          <div class="govuk-radios__item">
            <input class="govuk-radios__input" id="choice-username" name="choice" type="radio" value="username">
            <label class="govuk-label govuk-radios__label" for="choice-username">
              Username
            </label>
          </div>
        </div>
      </div>
      <%= form.submit 'Go to search', class: 'govuk-button' %>
    <% end %>
  </div>
</div>

app/views/logs_searches/contact.html.erb
<% content_for :page_title, "Search logs by user details" %>

<%= render "layouts/form_errors", resource: @search %>

<div class='govuk-grid-row'>
  <div class='govuk-grid-column-two-thirds'>
    <%= link_to "Back to search options", new_logs_search_path, class: "govuk-back-link" %>
  </div>

  <h1 class='govuk-heading-l govuk-grid-column-full'>Search for user details</h1>

  <div class='govuk-grid-column-two-thirds'>
    <%= form_with url: super_admin_wifi_user_search_path, local: true do |f| %>
      <p>
        <%= f.label :search_term, "Username, email address or phone number", class: "govuk-label", for: :search_term %>
        <%= f.text_field :search_term, class: "govuk-input govuk-input--width-50" %>
      </p>
      <p>
        <%= f.submit "Find user details", class: "govuk-button" %>
      </p>
    <% end %>

    <div class="govuk-body">
      <% if @wifi_user %>
        <h3>User details for '<%= params[:search_term] %>'</h3>
        <p>
          Username: <%= link_to @wifi_user.username,
                                logs_path(username: @wifi_user.username),
                                title: "Search logs for '#{@wifi_user.username}'" %>
        </p>
        <p>
          Contact: <%= @wifi_user.contact %>
        </p>
      <% elsif !params[:search_term].blank? %>
        <h3>Nothing found for '<%= params[:search_term] %>'</h3>
      <% end %>
    </div>
  </div>
</div>

app/views/logs_searches/ip.html.erb
<% content_for :page_title, "Search logs by IP address" %>

<%= render "layouts/form_errors", resource: @search %>

<div class='govuk-grid-row'>
  <div class='govuk-grid-column-two-thirds'>
    <%= link_to "Back to search options", new_logs_search_path, class: "govuk-back-link" %>
  </div>

  <h1 class='govuk-heading-l govuk-grid-column-full'>Search logs by IP address </h1>

  <div class='govuk-grid-column-two-thirds'>
    <%= form_for @search do |f| %>
      <div class='govuk-form-group <%= field_error(@search, :search_term) %>'>
        <%= f.label :search_term, "IP address", class: "govuk-label" %>
        <%= render "error_message", key: :search_term, message: "Enter a valid IP address" %>

        <%= f.text_field :search_term, class: "govuk-input govuk-input--width-10" %>
      </div>
      <%= f.hidden_field :filter %>
      <%= f.submit "Show logs", class: "govuk-button" %>
    <% end %>

    <p class='govuk-body'> Or, click "view logs" from <%= link_to "your list of IP addresses", ips_path %></p>
  </div>
</div>

app/views/logs_searches/location.html.erb
<% content_for :page_title, "Search logs by location" %>

<%= render "layouts/form_errors", resource: @search %>

<div class='govuk-grid-row'>
  <div class='govuk-grid-column-two-thirds'>
    <%= link_to "Back to search options", new_logs_search_path, class: "govuk-back-link" %>
  </div>

  <h1 class='govuk-heading-l govuk-grid-column-full'>Search logs by location </h1>

  <div class='govuk-grid-column-two-thirds'>
    <%= form_for @search do |f| %>
      <div class='govuk-form-group'>
        <%= f.label :search_term, "Select one of your organisation's locations", class: "govuk-label" %>
        <%= collection_select :logs_search, :search_term, @locations, :id, :full_address, {}, class: "govuk-select" %>
      </div>
      <%= f.hidden_field :filter %>
      <%= f.submit "Show logs", class: "govuk-button" %>
    <% end %>
  </div>
</div>

app/views/logs_searches/new.html.erb
<% content_for :page_title, "Start logs search" %>

<%= render "layouts/form_errors", resource: @search %>

<div class='govuk-grid-row'>
  <h1 class='govuk-heading-l govuk-grid-column-full'>Logs</h1>

  <div class='govuk-grid-column-full'>
    <p class='govuk-body'>
      Logs are kept for recent authentication requests made to the GovWifi service.
    </p>

    <%= form_with url: logs_searches_path, method: :post, local: true do |form| %>
      <div class="govuk-form-group">
        <div class="govuk-form-group">
          <fieldset class="govuk-fieldset">
            <legend class="govuk-fieldset__legend">
              How do you want to filter these logs?
            </legend>
            <div class="govuk-radios <%= field_error(@search, :filter) %>">
              <%= render "error_message", key: :filter, message: "select an option" %>
              <% if !super_admin? %>
                <div class="govuk-radios__item">
                  <input class="govuk-radios__input" id="choice-location" name="logs_search[filter]" type="radio" value="location">
                  <label class="govuk-label govuk-radios__label" for="choice-location">
                    Location
                  </label>
                </div>
              <% end %>
              <div class="govuk-radios__item">
                <input class="govuk-radios__input" id="choice-username" name="logs_search[filter]" type="radio" value="username">
                <label class="govuk-label govuk-radios__label" for="choice-username">
                  Username
                </label>
              </div>
              <div class="govuk-radios__item">
                <input class="govuk-radios__input" id="choice-ip" name="logs_search[filter]" type="radio" value="ip">
                <label class="govuk-label govuk-radios__label" for="choice-ip">
                  IP address
                </label>
              </div>
              <% if super_admin? %>
                <div class="govuk-radios__item">
                  <input class="govuk-radios__input" id="choice-email" name="logs_search[filter]" type="radio" value="contact">
                  <label class="govuk-label govuk-radios__label" for="choice-email">
                    Email address
                  </label>
                </div>
                <div class="govuk-radios__item">
                  <input class="govuk-radios__input" id="choice-phone" name="logs_search[filter]" type="radio" value="contact">
                  <label class="govuk-label govuk-radios__label" for="choice-phone">
                    Phone number
                  </label>
                </div>
              <% end %>
            </div>
          </fieldset>
        </div>
      </div>
      <input type='hidden' name='logs_search[first_step]' value='true'>
      <%= form.submit "Go to search", class: "govuk-button" %>
    <% end %>
  </div>
</div>

app/views/logs_searches/username.html.erb
<% content_for :page_title, "Search logs by username" %>

<%= render "layouts/form_errors", resource: @search %>

<div class='govuk-grid-row'>
  <div class='govuk-grid-column-two-thirds'>
    <%= link_to "Back to search options", new_logs_search_path, class: "govuk-back-link" %>
  </div>

  <h1 class='govuk-heading-l govuk-grid-column-full'>Search logs by username</h1>

  <div class='govuk-grid-column-two-thirds'>
    <%= form_for @search do |f| %>
      <div class='govuk-form-group <%= field_error(@search, :search_term) %>'>
        <%= f.label :search_term, "Username", class: "govuk-label" %>
        <span class='govuk-hint'>
          This is an end user's 5- or 6-character username, like 'abcdef'
        </span>
        <%= render "error_message", key: :search_term, message: "Enter a valid username" %>

        <%= f.text_field :search_term, class: "govuk-input govuk-input--width-10" %>
      </div>
      <%= f.hidden_field :filter %>
      <%= f.submit "Show logs", class: "govuk-button" %>
    <% end %>
  </div>
</div>