config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  devise_for :users,
             controllers: {
               confirmations: "users/confirmations",
               registrations: "users/registrations",
               invitations: "users/invitations",
               passwords: "users/passwords",
               two_factor_authentication: "users/two_factor_authentication",
             }

  devise_scope :user do
    put "users/confirmations", to: "users/confirmations#update"
    get "users/confirmations/pending", to: "users/confirmations#pending"

    put "users/two_factor_authentication_setup", to: "users/two_factor_authentication_setup#update"
    get "users/two_factor_authentication_setup", to: "users/two_factor_authentication_setup#show"

    get "users/:id/two_factor_authentication/edit", to: "users/two_factor_authentication#edit"
    delete "users/:id/two_factor_authentication", to: "users/two_factor_authentication#destroy"
  end
  get "confirm_new_membership", to: "users/memberships#create"

  get "/healthcheck", to: "monitoring#healthcheck"
  get "change_organisation", to: "current_organisation#edit"
  patch "change_organisation", to: "current_organisation#update"

  resources :status, only: %i[index]
  resources :ips, only: %i[index new create destroy] do
    get "remove", to: "ips#index"
    get "created", to: "ips#index", on: :collection
    get "created/location", to: "ips#index", on: :collection
    get "removed", to: "ips#index", on: :collection
    get "removed/location", to: "ips#index", on: :collection
  end

  resources :help, only: %i[create new] do
    get "/", on: :collection, to: "help#new"
    get "signed_in", on: :new
    get "admin_account", on: :new
    get "technical_support", on: :new
    get "user_support", on: :new
  end
  resources :locations, only: %i[new create destroy update] do
    get "remove", to: "ips#index"
    get "rotate_key", to: "ips#index"
    get "add_ips", to: "add_ips"
    patch "update_ips", to: "update_ips"
  end
  resources :memberships, only: %i[edit update index destroy] do
    collection do
      get "created/invite", to: "memberships#index"
      get "updated/permissions", to: "memberships#index"
      get "removed", to: "memberships#index"
    end
  end
  resources :mou, only: %i[index create] do
    collection do
      get "created", to: "mou#index"
      get "replaced", to: "mou#index"
    end
  end
  resources :logs, only: %i[index]
  resources :logs_searches, path: "logs/search", only: %i[new index create] do
    get "ip", on: :new
    get "username", on: :new
    get "location", on: :new
  end
  resources :organisations, only: %i[new create edit update]
  resources :settings, only: %i[index] do
    collection do
      get "initial", to: "settings#index", as: :new_organisation
    end
  end
  get "setup_instructions", to: redirect("settings")
  get "setup_instructions/:path", to: redirect("settings/%{path}")

  resources :overview, only: %i[index]

  namespace :super_admin do
    resources :locations, only: %i[index] do
      collection do
        get "map", to: "locations/map#index"
      end
    end
    resources :mou, only: %i[index update create]
    resources :organisations, only: %i[index show destroy] do
      collection do
        get "service_emails", to: "organisations#service_emails", constraints: { format: "csv" }
      end
    end
    resource :whitelist, only: %i[new create] do
      scope module: "whitelists" do
        resources :email_domains, only: %i[index new create destroy]
        resources :organisation_names, only: %i[index create destroy]
      end
    end

    post "wifi_user_search", to: "wifi_user_search#search"

    namespace "neo" do
      get "dashboard"
    end
  end

  %w[404 422 500].each do |code|
    get code, to: "application#error", code: code
  end
end

app/models/whitelist.rb
class Whitelist
  include ActiveModel::Model

  attr_accessor :email_domain, :organisation_name

  def save
    ActiveRecord::Base.transaction do
      CustomOrganisationName.create!(name: organisation_name) if organisation_name.present?
      AuthorisedEmailDomain.create!(name: email_domain) if email_domain.present?
    end

    true
  rescue ActiveRecord::RecordInvalid => e
    errors.add(:base, e.message)

    false
  end
end

app/controllers/super_admin/whitelists/email_domains_controller.rb
class SuperAdmin::Whitelists::EmailDomainsController < SuperAdminController
  helper_method :sort_column, :sort_direction

  def index
    @authorised_email_domains = AuthorisedEmailDomain.all.order("#{sort_column} #{sort_direction}")
  end

  def new
    @authorised_email_domain = AuthorisedEmailDomain.new
  end

  def create
    @authorised_email_domain = AuthorisedEmailDomain.new(authorised_email_params)

    if @authorised_email_domain.save
      publish_email_domains_regex
      publish_email_domains_list

      redirect_to super_admin_whitelist_email_domains_path, notice: "#{@authorised_email_domain.name} authorised"
    else
      render :new
    end
  end

  def destroy
    authorised_email_domain = AuthorisedEmailDomain.find_by(id: params.fetch(:id))

    authorised_email_domain.destroy!
    publish_email_domains_regex
    publish_email_domains_list

    redirect_to super_admin_whitelist_email_domains_path, notice: "#{authorised_email_domain.name} has been deleted"
  end

private

  def publish_email_domains_regex
    UseCases::Administrator::PublishSignupWhitelist.new(
      destination_gateway: Gateways::S3.new(
        bucket: ENV.fetch("S3_SIGNUP_WHITELIST_BUCKET"),
        key: ENV.fetch("S3_SIGNUP_WHITELIST_OBJECT_KEY"),
      ),
      source_gateway: Gateways::AuthorisedEmailDomains.new,
      presenter: UseCases::Administrator::FormatEmailDomainsRegex.new,
    ).execute
  end

  def publish_email_domains_list
    UseCases::Administrator::PublishSignupWhitelist.new(
      destination_gateway: Gateways::S3.new(
        bucket: ENV.fetch("S3_PRODUCT_PAGE_DATA_BUCKET"),
        key: ENV.fetch("S3_EMAIL_DOMAINS_OBJECT_KEY"),
      ),
      source_gateway: Gateways::AuthorisedEmailDomains.new,
      presenter: UseCases::Administrator::FormatEmailDomainsList.new,
    ).execute
  end

  def authorised_email_params
    params.require(:authorised_email_domain).permit(:name)
  end

  def sortable_columns
    %w[name]
  end

  def sortable_directions
    %w[asc]
  end

  def sort_column
    sortable_columns.include?(params[:sort]) ? params[:sort] : sortable_columns.first
  end

  def sort_direction
    sortable_directions.include?(params[:direction]) ? params[:direction] : sortable_directions.first
  end
end

app/controllers/super_admin/whitelists/organisation_names_controller.rb
class SuperAdmin::Whitelists::OrganisationNamesController < SuperAdminController
  helper_method :sort_column, :sort_direction

  before_action :set_organisations_from_register, only: %i[create index]

  def index
    @custom_organisation_names = ordered_custom_orgs
    @custom_organisation = CustomOrganisationName.new
  end

  def create
    @custom_organisation_names = ordered_custom_orgs
    @custom_organisation = CustomOrganisationName.new(custom_org_params)

    if @custom_organisation.save
      redirect_to super_admin_whitelist_organisation_names_path, notice: "Custom organisation has been successfully added"
    else
      render :index
    end
  end

  def destroy
    custom_org = CustomOrganisationName.find(params.fetch(:id))

    custom_org.destroy!
    redirect_to super_admin_whitelist_organisation_names_path, notice: "Successfully removed #{custom_org.name}"
  end

private

  def custom_org_params
    params.require(:custom_organisations).permit(:name)
  end

  def ordered_custom_orgs
    CustomOrganisationName.all.order("#{sort_column} #{sort_direction}")
  end

  def sortable_columns
    %w[name]
  end

  def sortable_directions
    %w[asc]
  end

  def sort_column
    sortable_columns.include?(params[:sort]) ? params[:sort] : sortable_columns.first
  end

  def sort_direction
    sortable_directions.include?(params[:direction]) ? params[:direction] : sortable_directions.first
  end

  def set_organisations_from_register
    @fetched_organisations_from_register = Organisation.fetch_organisations_from_register
  end
end

app/controllers/super_admin/whitelists_controller.rb
class SuperAdmin::WhitelistsController < SuperAdminController
  def new
    @whitelist = Whitelist.new
    @organisation_names = Organisation.fetch_organisations_from_register
    validate_organisation_name if organisation_name_needs_validation?
    validate_email_domain if email_domain_needs_validation?
  end

  def create
    @whitelist = Whitelist.new(
      organisation_name: whitelist_params[:organisation_name],
      email_domain: whitelist_params[:email_domain],
    )
    if @whitelist.save
      publish_email_domains_regex
      publish_email_domains_list

      redirect_to new_super_admin_whitelist_path,
                  notice: "Organisation has been added to the allow list"
    else
      redirect_to new_super_admin_whitelist_path(step: "fourth"),
                  notice: "There was an error, please try again"
    end
  end

private

  def publish_email_domains_regex
    UseCases::Administrator::PublishSignupWhitelist.new(
      destination_gateway: Gateways::S3.new(
        bucket: ENV.fetch("S3_SIGNUP_WHITELIST_BUCKET"),
        key: ENV.fetch("S3_SIGNUP_WHITELIST_OBJECT_KEY"),
      ),
      source_gateway: Gateways::AuthorisedEmailDomains.new,
      presenter: UseCases::Administrator::FormatEmailDomainsRegex.new,
    ).execute
  end

  def publish_email_domains_list
    UseCases::Administrator::PublishSignupWhitelist.new(
      destination_gateway: Gateways::S3.new(
        bucket: ENV.fetch("S3_PRODUCT_PAGE_DATA_BUCKET"),
        key: ENV.fetch("S3_EMAIL_DOMAINS_OBJECT_KEY"),
      ),
      source_gateway: Gateways::AuthorisedEmailDomains.new,
      presenter: UseCases::Administrator::FormatEmailDomainsList.new,
    ).execute
  end

  def organisation_name_needs_validation?
    organisation_name_submitted? && organisation_name_not_yet_validated?
  end

  def organisation_name_submitted?
    params.dig(:whitelist, :organisation_name).present?
  end

  def organisation_name_not_yet_validated?
    !!!whitelist_params[:organisation_name_valid]
  end

  def validate_organisation_name
    @organisation_name = CustomOrganisationName.new(name: whitelist_params[:organisation_name])
    if @organisation_name.invalid?
      send_user_back_to_organisation_name_form
    else
      mark_organisation_name_as_validated
    end
  end

  def send_user_back_to_organisation_name_form
    params[:whitelist][:step] = "fourth"
  end

  def mark_organisation_name_as_validated
    params[:whitelist][:organisation_name_valid] = true
  end

  def email_domain_needs_validation?
    params.dig(:whitelist, :email_domain).present?
  end

  def validate_email_domain
    @email_domain = AuthorisedEmailDomain.new(name: whitelist_params[:email_domain])
    if @email_domain.invalid?
      send_user_back_to_email_domain_form
    end
  end

  def send_user_back_to_email_domain_form
    params[:whitelist][:step] = "fifth"
  end

  def whitelist_params
    params.require(:whitelist).permit(:email_domain, :organisation_name, :organisation_name_valid)
  end
end

app/views/super_admin/whitelists/email_domains/_confirm_remove_email_domain.html.erb
<div class="govuk-error-summary" role="alert">
  <h2 class="govuk-error-summary__title">
    Are you sure you want to remove this email domain?
  </h2>
  <div class="govuk-error-summary__body">
    <%= button_to "Yes, remove #{params[:domain_to_remove]} from the allow list", super_admin_whitelist_email_domain_path(params[:id]), method: :delete, class: "govuk-button red-button" %>
  </div>
</div>

app/views/super_admin/whitelists/email_domains/_table.html.erb
<table class="govuk-table govuk-!-margin-bottom-8">
    <thead class="govuk-table__head">
      <tr class="govuk-table__row">
        <th class="govuk-table__header" scope="col">Email Domain</th>
        <th class="govuk-table__header" scope="col">Date Added</th>
        <th class="govuk-table__header" scope="col"></th>
      </tr>
    </thead>
  <tbody class="govuk-table__body" id="domains-table">
    <% domains.each do |domain| %>
      <tr class="govuk-table__row">
        <td class="govuk-table__cell govuk-!-width-one-third"><%= domain.name %></td>
        <td class="govuk-table__cell"><%= domain.created_at.strftime("%e %b %Y") %></td>
        <td class="govuk-table__cell text-right">
          <%= link_to "Remove", super_admin_whitelist_email_domains_path(id: domain.id, domain_to_remove: domain.name), class: "govuk-link" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/super_admin/whitelists/email_domains/index.html.erb
<% content_for :page_title, "Manage allowed email domains" %>

<%= render "confirm_remove_email_domain" if params[:domain_to_remove] %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-one-quarter">
    <%= render "super_admin/whitelists/side_nav" %>
  </div>
  <div class="govuk-grid-column-three-quarters">
    <div class="govuk-grid-row">
      <div class="govuk-grid-column-two-thirds">
        <h1 class="govuk-heading-l">Email domains allow list</h1>
      </div>

      <div class="govuk-grid-column-one-third text-right">
        <%= link_to "Allow a domain", new_super_admin_whitelist_email_domain_path, class: "govuk-button", role: "button", draggable: "false", "data-module" => "govuk-button" %>
      </div>
    </div>

     <%= render "super_admin/whitelists/email_domains/table", domains: @authorised_email_domains %>
  </div>
</div>

app/views/super_admin/whitelists/email_domains/new.html.erb
<%= render "layouts/form_errors", resource: @authorised_email_domain %>

<% content_for :page_title, "Approve a new email domain" %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">

    <h1 class="govuk-heading-l">Allow a new email domain</h1>

    <%= form_for @authorised_email_domain, url: { action: :create } do |f| %>
      <%= f.label :name, "Name", class: "govuk-label" %>
      <%= f.text_field :name, class: "govuk-input govuk-input--width-10" %>

      <%= f.submit "Save", class: "govuk-button" %>
    <% end %>
  </div>
</div>